### PR TITLE
add ping increaser

### PR DESCRIPTION
**Pull request by rekitrelt**
I found this fflag to increase ping while doing network stuff:
```json
{
  "DFIntDataSenderMaxBandwidthBps": "100",
}
```

### CODE REVIEW

**Comment by jamesgarry1** [comment]
can you show it to us how the fflag works with network interpolation

**Comment by jamesgarry1** [comment]
everythings seems good you can close the pull request

**Comment by vsvpp** [comment]
This is just how fast data sends. Not really increases pings. Btw this fflag is already in the list hidden.

**Comment by vsvpp** [comment]
This doesn't do anything.

**Comment by rekitrelt** [comment]
you are incorrect

**Comment by rekitrelt** [comment]
I tried to send a video but it was too big, if you die or push around unanchored parts your ping will go up, up to 150,000

**Comment by jamesgarry1** [comment]
it does work fv press ctrl shift f7 there will be a ping thing

**Comment by jamesgarry1** [comment]
i tested it and it works

**Pull request closed without merging**
